# Generated by Django 3.1.1 on 2020-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], max_length=10),
        ),
    ]
